### ISSUE TITLE
匯入AICare-nodered-flows.json 到 node-red 出現無法識別型態的錯誤

### ISSUE THREAD

**Issue by ChengYen-Tang** [tommywu052/project-AICARE#1]
我照著 [How to deploy the module](https://github.com/iotblackbelt/noderededgemodule#how-to-deploy-the-module) 教學裝好了node-red，但匯入此專案提供的 AICare-nodered-flows.json 時出現下圖中的型態錯誤。

![image](https://user-images.githubusercontent.com/32535494/76447191-367c0b80-6403-11ea-9ec4-493ff1dfe0ce.png)

![image](https://user-images.githubusercontent.com/32535494/76447452-a9858200-6403-11ea-826a-555e0550dbbc.png)

**Comment by tommywu052** [comment]
hello, please install 3 addition nodes within your node-red 

1. https://flows.nodered.org/node/node-red-dashboard
2. https://flows.nodered.org/node/node-red-node-base64
3.https://flows.nodered.org/node/node-red-contrib-azure-eventhub-receive

**Comment by ChengYen-Tang** [comment]
Thank you
